# Generated by Django 3.0.2 on 2020-01-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_number', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('movie', models.CharField(max_length=50)),
                ('sub_chapter', models.CharField(max_length=2)),
                ('hit_count', models.CharField(max_length=10)),
                ('download_count', models.CharField(max_length=10)),
                ('disk_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Demo_number')),
            ],
            options={
                'ordering': ('demo_number',),
            },
        ),
    ]
