# Generated by Django 3.0.2 on 2020-01-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200110_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='sn',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='demo',
            name='disk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Disk'),
        ),
    ]
