# Generated by Django 3.0.2 on 2020-01-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_demo_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='disk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Disk'),
        ),
    ]
