# Generated by Django 3.0.2 on 2020-01-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_remove_demo_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='disk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.Disk'),
        ),
    ]
